AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AcmCertificateArn:
    Type: String
  CredentialsFunctionVersion:
    Type: String
  DomainName:
    Type: String
  Env:
    Type: String
  HostedZoneName:
    Type: String
  WebBucketName:
    Type: String

Resources:

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt AccessIdentity.S3CanonicalUserId
            Action:
              - s3:*
            Resource: !Sub 'arn:aws:s3:::${WebBucketName}/*'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: !Ref CredentialsFunctionVersion
          TargetOriginId: default-origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: default-origin
            DomainName: !Sub '${WebBucketName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${AccessIdentity}'
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  AccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${DomainName}'

  DnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: Alias targeting CloudFront for git-visualized-activity
      RecordSets:
        - Name: !Sub '${DomainName}.'
          Type: A
          AliasTarget:
            # Special value for CloudFront.
            # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#w2ab1c17c23c81c11
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName

  CloudFrontDistributionIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/git-visualized-activity/${Env}/cf-distribution-id'
      Value: !Ref Distribution
      Type: String

Outputs:
  CloudFrontDistributionId:
    Value: !Ref Distribution
  CloudFrontDomainName:
    Value: !GetAtt Distribution.DomainName
