AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AssumedJenkinsRoleArn:
    Type: String
  CfDistributionId:
    Type: String
  DeployCodeS3Bucket:
    Type: String
  DeployCodeS3Key:
    Type: String
  FunctionName:
    Type: String
  ReleasesBucketName:
    Type: String
  TargetBucketName:
    Type: String

Resources:

  DeployFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeployCodeS3Bucket
        S3Key: !Ref DeployCodeS3Key
      Environment:
        Variables:
          TARGET_BUCKET_URL: !Sub 's3://${TargetBucketName}/web'
          DEPLOY_LOG_BUCKET_URL: !Sub 's3://${TargetBucketName}/deployments.log'
          CF_DISTRIBUTION_ID: !Ref CfDistributionId
      Handler: webapp_deploy.main.handler
      FunctionName: !Ref FunctionName
      MemorySize: 128
      ReservedConcurrentExecutions: 1
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.7
      Timeout: 120

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: custom
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - s3:HeadObject
                - s3:GetObject
              Resource: !Sub 'arn:aws:s3:::${ReleasesBucketName}/*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::${TargetBucketName}/web/*'
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${TargetBucketName}/deployments.log'
            - Effect: Allow
              Action:
                - cloudfront:CreateInvalidation
              Resource: '*' # Cannot be restricted

  DeployPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeployFunction
      Action: lambda:InvokeFunction
      Principal: !Ref AssumedJenkinsRoleArn
