name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Generate snapshots
        run: make snapshots
      - name: Check for snapshots diff
        run: |
          git status
          git diff --exit-code
